### ISSUE TITLE
WARN  - hid-handler:91 - 46.8s - error received : { [Error: LIBUSB_TRANSFER_ERROR] errno: 1 }

### ISSUE THREAD

**Issue by ivanchoff** [openhoat/hid-handler#1]
in my app i use a ring presenter for control my app (playlist and more) i am runnig on raspberry (raspbian) and the app run normally for a while until past few minutes i get this error and the system reboot.

```
WARN  - hid-handler:91 - 46.8s - error received : { [Error: LIBUSB_TRANSFER_ERROR] errno: 1 }
WARN  - hid-handler:91 - 281ms - error received : { [Error: LIBUSB_TRANSFER_ERROR] errno: 1 }
WARN  - hid-handler:91 - 12ms - error received : { [Error: LIBUSB_TRANSFER_ERROR] errno: 1 }
Unhandled rejection TypeError: type.split is not a function
    at /home/pi/app/raspi/node_modules/hid-handler/lib/hid-handler.js:189:19
    at /home/pi/app/raspi/node_modules/lodash/index.js:3073:15
    at Function.forIn (/home/pi/app/raspi/node_modules/lodash/index.js:3362:16)
    at initHid (/home/pi/app/raspi/node_modules/hid-handler/lib/hid-handler.js:177:11)
    at tryCatcher (/home/pi/app/raspi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/app/raspi/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/pi/app/raspi/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/pi/app/raspi/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/pi/app/raspi/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/pi/app/raspi/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/pi/app/raspi/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/app/raspi/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

so i don't know what is really happening... 
thanks in advance

**Comment by openhoat** [comment]
Hello,

I just fixed it, could you try again ?
